#
# docker-compose.yml
#
# Docker compose file for MySQL to support Bankly App
#
# Key Considerations:
# - MySQL service is on a single external bridge network
#
# Author: Gonzalo Vazquez
#

version: '2'

#
# Services
#
services:

    #
    # MySQL database
    #
    mysqldb:
      image: mysql:5.7.16
      volumes:
        - ./db/mysql:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: my-secret-pw
      ports:
        - "3306:3306"
    
    #
    # Chore Services
    #
    chores:
      image: usmakestwo/chore-service:1.0.1
      volumes:
        - ./etc/db/mysql/config/chore-service:/config
      depends_on:
        - mysqldb
      links:
        - mysqldb
      ports:
        - "8080:8080"

#
# Networks
#
networks:
    localnet:
        # driver: bridge
        external: true