---
singletons:
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      jdbcUrl: jdbc:mysql://mysqldb:3306/chores?useSSL=false
      username: root
      password: my-secret-pw
      maximumPoolSize: 15