---
singletons:
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      jdbcUrl: jdbc:postgresql://postgresdb:5432/chores
      username: postgres
      password: my-secret-pw
      maximumPoolSize: 15